// Recetario base. Cada ingrediente es [nombre, cantidad].
// Los nombres deben coincidir con los de la despensa (se ignoran mayúsculas, tildes y plurales).
// Para agregar más recetas usa el botón "Nueva receta" dentro de la app (se guardan en la base de datos),
// o agrega objetos aquí siguiendo el mismo formato.

export const BASICOS = ['sal', 'pimienta', 'agua'];

export const RECETAS_BASE = [
  // ───────── Desayunos ─────────
  { id: 'r01', name: 'Huevos revueltos', emoji: '🍳', cat: 'Desayuno', time: '10 min', diff: 1,
    ing: [['huevo', '3'], ['mantequilla', '1 cda'], ['leche', '2 cdas'], ['sal', 'a gusto']],
    steps: ['Bate los huevos con la leche y una pizca de sal.', 'Derrite la mantequilla en un sartén a fuego bajo.', 'Agrega los huevos y revuelve suave hasta que cuajen.', 'Sirve de inmediato.'] },
  { id: 'r02', name: 'Panqueques', emoji: '🥞', cat: 'Desayuno', time: '25 min', diff: 2,
    ing: [['harina', '1 taza'], ['leche', '1 taza'], ['huevo', '2'], ['azúcar', '1 cda'], ['mantequilla', '1 cda']],
    steps: ['Mezcla harina, azúcar, huevos y leche hasta que no queden grumos.', 'Calienta un sartén con un poco de mantequilla.', 'Vierte un cucharón de mezcla y gira el sartén para cubrir.', 'Dora por ambos lados y rellena con lo que quieras.'] },
  { id: 'r03', name: 'Avena con plátano', emoji: '🥣', cat: 'Desayuno', time: '10 min', diff: 1,
    ing: [['avena', '1/2 taza'], ['leche', '1 taza'], ['plátano', '1'], ['canela', 'pizca']],
    steps: ['Calienta la leche con la avena revolviendo 5 minutos.', 'Agrega el plátano en rodajas.', 'Espolvorea canela y sirve.'] },
  { id: 'r04', name: 'Tostadas con palta', emoji: '🥑', cat: 'Desayuno', time: '5 min', diff: 1,
    ing: [['pan', '2 rebanadas'], ['palta', '1'], ['limón', '1/2'], ['sal', 'a gusto']],
    steps: ['Tuesta el pan.', 'Muele la palta con jugo de limón y sal.', 'Unta sobre el pan tostado.'] },
  { id: 'r05', name: 'Smoothie de frutilla', emoji: '🍓', cat: 'Desayuno', time: '5 min', diff: 1,
    ing: [['frutilla', '1 taza'], ['plátano', '1'], ['yogur', '1'], ['leche', '1/2 taza']],
    steps: ['Pon todo en la licuadora.', 'Licúa hasta que quede cremoso.', 'Sirve frío.'] },
  { id: 'r06', name: 'Omelette de queso y jamón', emoji: '🧀', cat: 'Desayuno', time: '10 min', diff: 1,
    ing: [['huevo', '2'], ['queso', '1 lámina'], ['jamón', '1 lámina'], ['mantequilla', '1 cdta']],
    steps: ['Bate los huevos con sal.', 'Viértelos en un sartén con mantequilla caliente.', 'Cuando cuajen, pon queso y jamón en una mitad.', 'Dobla y sirve.'] },
  { id: 'r07', name: 'Yogur con granola y fruta', emoji: '🍨', cat: 'Desayuno', time: '3 min', diff: 1,
    ing: [['yogur', '1'], ['granola', '3 cdas'], ['manzana', '1/2']],
    steps: ['Pon el yogur en un pocillo.', 'Agrega la fruta picada y la granola encima.'] },
  { id: 'r08', name: 'Pan francés', emoji: '🍞', cat: 'Desayuno', time: '15 min', diff: 1,
    ing: [['pan', '4 rebanadas'], ['huevo', '2'], ['leche', '1/2 taza'], ['canela', 'pizca'], ['mantequilla', '1 cda'], ['azúcar', '1 cda']],
    steps: ['Bate huevos, leche, azúcar y canela.', 'Remoja cada rebanada de pan en la mezcla.', 'Dora en mantequilla por ambos lados.'] },

  // ───────── Almuerzos / Cenas ─────────
  { id: 'r09', name: 'Fideos con salsa de tomate', emoji: '🍝', cat: 'Almuerzo', time: '25 min', diff: 1,
    ing: [['fideos', '250 g'], ['salsa de tomate', '1 caja'], ['cebolla', '1'], ['ajo', '1 diente'], ['aceite', '1 cda'], ['queso', 'para rallar']],
    steps: ['Cuece los fideos en agua con sal.', 'Sofríe cebolla y ajo picados en aceite.', 'Agrega la salsa de tomate y cocina 10 min.', 'Mezcla con los fideos y pon queso encima.'] },
  { id: 'r10', name: 'Fideos con carne molida (boloñesa)', emoji: '🍝', cat: 'Almuerzo', time: '35 min', diff: 2,
    ing: [['fideos', '250 g'], ['carne molida', '300 g'], ['salsa de tomate', '1 caja'], ['cebolla', '1'], ['zanahoria', '1'], ['aceite', '1 cda']],
    steps: ['Sofríe la cebolla y la zanahoria rallada.', 'Agrega la carne y dora bien.', 'Suma la salsa de tomate y cocina 15 min.', 'Sirve sobre los fideos cocidos.'] },
  { id: 'r11', name: 'Arroz graneado', emoji: '🍚', cat: 'Almuerzo', time: '25 min', diff: 1,
    ing: [['arroz', '1 taza'], ['aceite', '1 cda'], ['ajo', '1 diente'], ['agua', '2 tazas']],
    steps: ['Sofríe el arroz con el ajo en aceite 2 min.', 'Agrega 2 tazas de agua caliente y sal.', 'Tapa y cocina a fuego bajo 18 min sin destapar.', 'Suelta con un tenedor.'] },
  { id: 'r12', name: 'Pollo al horno con papas', emoji: '🍗', cat: 'Almuerzo', time: '60 min', diff: 2,
    ing: [['pollo', '4 presas'], ['papa', '4'], ['ajo', '2 dientes'], ['aceite', '2 cdas'], ['orégano', '1 cdta']],
    steps: ['Precalienta el horno a 200 °C.', 'Corta las papas en gajos y ponlas en una fuente con el pollo.', 'Agrega aceite, ajo, orégano y sal.', 'Hornea 50 min dando vuelta a la mitad.'] },
  { id: 'r13', name: 'Arroz con pollo', emoji: '🥘', cat: 'Almuerzo', time: '45 min', diff: 2,
    ing: [['arroz', '1 taza'], ['pollo', '2 presas'], ['cebolla', '1'], ['pimentón', '1'], ['arvejas', '1/2 taza'], ['aceite', '1 cda']],
    steps: ['Dora el pollo en una olla con aceite.', 'Agrega cebolla y pimentón picados.', 'Suma arroz, arvejas y 2 tazas de agua con sal.', 'Tapa y cocina 20 min a fuego bajo.'] },
  { id: 'r14', name: 'Tortilla de papas', emoji: '🥔', cat: 'Almuerzo', time: '40 min', diff: 2,
    ing: [['papa', '4'], ['huevo', '5'], ['cebolla', '1'], ['aceite', '1/2 taza']],
    steps: ['Corta papas y cebolla en láminas finas.', 'Fríelas a fuego medio hasta que estén blandas.', 'Escúrrelas y mézclalas con los huevos batidos.', 'Cuaja en sartén por un lado, da vuelta con un plato y termina.'] },
  { id: 'r15', name: 'Lentejas guisadas', emoji: '🍲', cat: 'Almuerzo', time: '50 min', diff: 2,
    ing: [['lentejas', '2 tazas'], ['cebolla', '1'], ['zanahoria', '1'], ['zapallo', '1 trozo'], ['arroz', '1/4 taza'], ['comino', 'pizca']],
    steps: ['Remoja las lentejas una noche (opcional).', 'Sofríe cebolla y zanahoria picadas.', 'Agrega lentejas, zapallo en cubos y agua hasta cubrir.', 'Cocina 30 min; suma el arroz los últimos 15 min.'] },
  { id: 'r16', name: 'Porotos con riendas', emoji: '🫘', cat: 'Almuerzo', time: '60 min', diff: 2,
    ing: [['porotos', '2 tazas'], ['fideos', '100 g'], ['zapallo', '1 trozo'], ['cebolla', '1'], ['pimentón', '1']],
    steps: ['Cuece los porotos remojados hasta que estén blandos.', 'Sofríe cebolla y pimentón, y agrégalos a la olla con el zapallo.', 'Suma los fideos (tallarines cortados) y cocina 10 min más.'] },
  { id: 'r17', name: 'Hamburguesas caseras', emoji: '🍔', cat: 'Cena', time: '25 min', diff: 2,
    ing: [['carne molida', '500 g'], ['huevo', '1'], ['pan rallado', '3 cdas'], ['pan de hamburguesa', '4'], ['lechuga', 'hojas'], ['tomate', '1']],
    steps: ['Mezcla carne, huevo, pan rallado y sal.', 'Forma 4 discos aplanados.', 'Cocina en sartén 4 min por lado.', 'Arma con pan, lechuga y tomate.'] },
  { id: 'r18', name: 'Quesadillas', emoji: '🌮', cat: 'Cena', time: '10 min', diff: 1,
    ing: [['tortillas', '4'], ['queso', '4 láminas'], ['jamón', '4 láminas']],
    steps: ['Pon queso y jamón en media tortilla.', 'Dobla y dora en sartén sin aceite por ambos lados.', 'Corta en triángulos.'] },
  { id: 'r19', name: 'Pizza en pan pita', emoji: '🍕', cat: 'Cena', time: '15 min', diff: 1,
    ing: [['pan pita', '2'], ['salsa de tomate', '4 cdas'], ['queso', '1 taza rallado'], ['jamón', '2 láminas'], ['orégano', 'pizca']],
    steps: ['Unta salsa sobre el pan pita.', 'Agrega queso, jamón y orégano.', 'Hornea a 200 °C por 8–10 min.'] },
  { id: 'r20', name: 'Sopa de verduras', emoji: '🥕', cat: 'Cena', time: '40 min', diff: 1,
    ing: [['zanahoria', '2'], ['papa', '2'], ['zapallo', '1 trozo'], ['cebolla', '1'], ['fideos', '1 puñado']],
    steps: ['Pica todas las verduras en cubos.', 'Hiérvelas en agua con sal 20 min.', 'Agrega los fideos y cocina 8 min más.'] },
  { id: 'r21', name: 'Puré de papas', emoji: '🥔', cat: 'Almuerzo', time: '30 min', diff: 1,
    ing: [['papa', '5'], ['leche', '1/2 taza'], ['mantequilla', '2 cdas'], ['sal', 'a gusto']],
    steps: ['Pela y cuece las papas en agua con sal.', 'Escúrrelas y muélelas.', 'Agrega leche caliente y mantequilla, mezcla hasta que quede suave.'] },
  { id: 'r22', name: 'Milanesas de pollo', emoji: '🍗', cat: 'Almuerzo', time: '30 min', diff: 2,
    ing: [['pechuga de pollo', '2'], ['huevo', '2'], ['pan rallado', '1 taza'], ['aceite', 'para freír']],
    steps: ['Corta la pechuga en filetes delgados.', 'Pásalos por huevo batido y luego por pan rallado.', 'Fríe en aceite caliente hasta dorar por ambos lados.'] },
  { id: 'r23', name: 'Ensalada chilena', emoji: '🍅', cat: 'Almuerzo', time: '10 min', diff: 1,
    ing: [['tomate', '3'], ['cebolla', '1'], ['aceite', '1 cda'], ['cilantro', 'opcional']],
    steps: ['Corta la cebolla en pluma y lávala con agua caliente.', 'Corta los tomates en gajos.', 'Mezcla y aliña con aceite y sal.'] },
  { id: 'r24', name: 'Ensalada de atún', emoji: '🥗', cat: 'Cena', time: '10 min', diff: 1,
    ing: [['atún', '1 lata'], ['lechuga', '1/2'], ['tomate', '1'], ['choclo', '1/2 taza'], ['huevo', '1 duro']],
    steps: ['Lava y corta la lechuga.', 'Agrega tomate, choclo, huevo duro y atún escurrido.', 'Aliña a gusto.'] },
  { id: 'r25', name: 'Arroz con atún y choclo', emoji: '🐟', cat: 'Almuerzo', time: '25 min', diff: 1,
    ing: [['arroz', '1 taza'], ['atún', '1 lata'], ['choclo', '1/2 taza'], ['mayonesa', '2 cdas']],
    steps: ['Cocina el arroz y déjalo enfriar un poco.', 'Mezcla con atún, choclo y mayonesa.', 'Sirve tibio o frío.'] },
  { id: 'r26', name: 'Guiso de zapallo italiano', emoji: '🥒', cat: 'Almuerzo', time: '30 min', diff: 2,
    ing: [['zapallo italiano', '3'], ['cebolla', '1'], ['choclo', '1/2 taza'], ['huevo', '2'], ['queso', '1/2 taza rallado']],
    steps: ['Sofríe la cebolla picada.', 'Agrega el zapallo italiano en cubos y el choclo; cocina 10 min.', 'Incorpora los huevos batidos revolviendo.', 'Termina con queso encima.'] },
  { id: 'r27', name: 'Pastel de papas', emoji: '🥧', cat: 'Almuerzo', time: '60 min', diff: 3,
    ing: [['papa', '6'], ['carne molida', '500 g'], ['cebolla', '2'], ['leche', '1/2 taza'], ['mantequilla', '2 cdas'], ['queso', 'para gratinar']],
    steps: ['Prepara un puré con papas, leche y mantequilla.', 'Sofríe cebolla y carne con comino y sal.', 'En una fuente pon la carne y cubre con el puré.', 'Agrega queso y gratina 20 min a 200 °C.'] },
  { id: 'r28', name: 'Wrap de pollo', emoji: '🌯', cat: 'Cena', time: '20 min', diff: 1,
    ing: [['tortillas', '2'], ['pechuga de pollo', '1'], ['lechuga', 'hojas'], ['tomate', '1'], ['mayonesa', '1 cda']],
    steps: ['Cocina el pollo en tiras en un sartén.', 'Unta mayonesa en la tortilla.', 'Agrega lechuga, tomate y pollo.', 'Enrolla y corta a la mitad.'] },
  { id: 'r29', name: 'Garbanzos salteados', emoji: '🧆', cat: 'Almuerzo', time: '20 min', diff: 1,
    ing: [['garbanzos', '1 lata'], ['cebolla', '1'], ['pimentón', '1'], ['comino', 'pizca'], ['aceite', '1 cda']],
    steps: ['Sofríe cebolla y pimentón en tiras.', 'Agrega los garbanzos escurridos y el comino.', 'Saltea 5 min y sirve con arroz.'] },
  { id: 'r30', name: 'Salchichas con puré', emoji: '🌭', cat: 'Cena', time: '30 min', diff: 1,
    ing: [['vienesas', '6'], ['papa', '5'], ['leche', '1/2 taza'], ['mantequilla', '2 cdas']],
    steps: ['Prepara el puré de papas.', 'Cuece o dora las vienesas.', 'Sirve juntas.'] },
  { id: 'r31', name: 'Fideos con mantequilla y queso', emoji: '🧈', cat: 'Cena', time: '15 min', diff: 1,
    ing: [['fideos', '200 g'], ['mantequilla', '2 cdas'], ['queso', '1/2 taza rallado']],
    steps: ['Cuece los fideos.', 'Escúrrelos y mézclalos con mantequilla.', 'Agrega queso rallado y sirve.'] },
  { id: 'r32', name: 'Champiñones salteados', emoji: '🍄', cat: 'Cena', time: '15 min', diff: 1,
    ing: [['champiñones', '250 g'], ['ajo', '2 dientes'], ['mantequilla', '1 cda'], ['perejil', 'opcional']],
    steps: ['Lamina los champiñones.', 'Saltéalos en mantequilla con ajo hasta dorar.', 'Sirve como acompañamiento o sobre pan.'] },
  { id: 'r33', name: 'Huevos con arroz y palta', emoji: '🍳', cat: 'Almuerzo', time: '25 min', diff: 1,
    ing: [['arroz', '1 taza'], ['huevo', '2'], ['palta', '1'], ['aceite', '1 cda']],
    steps: ['Cocina el arroz.', 'Fríe los huevos.', 'Sirve el arroz con huevo y palta en láminas.'] },
  { id: 'r34', name: 'Crema de zapallo', emoji: '🎃', cat: 'Cena', time: '35 min', diff: 1,
    ing: [['zapallo', '500 g'], ['cebolla', '1'], ['papa', '1'], ['crema', '1/2 caja']],
    steps: ['Cuece zapallo, papa y cebolla en agua con sal.', 'Licúa todo con parte del líquido.', 'Agrega la crema y calienta sin hervir.'] },
  { id: 'r35', name: 'Sándwich caliente', emoji: '🥪', cat: 'Snack', time: '8 min', diff: 1,
    ing: [['pan', '2 rebanadas'], ['queso', '2 láminas'], ['jamón', '2 láminas'], ['mantequilla', '1 cdta']],
    steps: ['Arma el sándwich con jamón y queso.', 'Unta mantequilla por fuera.', 'Dóralo en sartén o sandwichera hasta que el queso se derrita.'] },
  { id: 'r36', name: 'Carne mechada rápida', emoji: '🥩', cat: 'Almuerzo', time: '50 min', diff: 3,
    ing: [['carne', '500 g'], ['cebolla', '1'], ['zanahoria', '1'], ['pimentón', '1'], ['salsa de tomate', '1/2 caja']],
    steps: ['Cuece la carne en olla a presión 30 min.', 'Desmenúzala con dos tenedores.', 'Sofríe las verduras, agrega carne y salsa, cocina 10 min.'] },
  { id: 'r37', name: 'Pollo salteado con verduras', emoji: '🥢', cat: 'Cena', time: '25 min', diff: 2,
    ing: [['pechuga de pollo', '1'], ['zanahoria', '1'], ['pimentón', '1'], ['cebolla', '1'], ['salsa de soya', '2 cdas'], ['aceite', '1 cda']],
    steps: ['Corta todo en tiras.', 'Saltea el pollo en aceite bien caliente.', 'Agrega verduras y saltea 5 min.', 'Termina con salsa de soya. Sirve con arroz.'] },

  // ───────── Snacks ─────────
  { id: 'r38', name: 'Palomitas de maíz', emoji: '🍿', cat: 'Snack', time: '8 min', diff: 1,
    ing: [['maíz para cabritas', '1/2 taza'], ['aceite', '2 cdas'], ['sal', 'a gusto']],
    steps: ['Calienta aceite en una olla con tapa.', 'Agrega el maíz y tapa.', 'Mueve la olla hasta que deje de reventar.'] },
  { id: 'r39', name: 'Guacamole con nachos', emoji: '🥑', cat: 'Snack', time: '10 min', diff: 1,
    ing: [['palta', '2'], ['tomate', '1'], ['cebolla', '1/4'], ['limón', '1'], ['nachos', '1 bolsa']],
    steps: ['Muele las paltas.', 'Agrega tomate y cebolla muy picados, limón y sal.', 'Sirve con nachos.'] },
  { id: 'r40', name: 'Manzanas asadas', emoji: '🍎', cat: 'Snack', time: '30 min', diff: 1,
    ing: [['manzana', '4'], ['azúcar', '2 cdas'], ['canela', '1 cdta'], ['mantequilla', '1 cda']],
    steps: ['Saca el centro de las manzanas.', 'Rellena con azúcar, canela y mantequilla.', 'Hornea 25 min a 180 °C.'] },
  { id: 'r41', name: 'Huevos duros rellenos', emoji: '🥚', cat: 'Snack', time: '20 min', diff: 1,
    ing: [['huevo', '4'], ['mayonesa', '2 cdas'], ['atún', '1/2 lata']],
    steps: ['Cuece los huevos 10 min y enfría.', 'Pártelos y saca las yemas.', 'Mezcla yemas con mayonesa y atún, y rellena.'] },

  // ───────── Postres ─────────
  { id: 'r42', name: 'Queque de vainilla', emoji: '🍰', cat: 'Postre', time: '50 min', diff: 2,
    ing: [['harina', '2 tazas'], ['azúcar', '1 taza'], ['huevo', '3'], ['leche', '1/2 taza'], ['mantequilla', '100 g'], ['polvo de hornear', '2 cdtas'], ['vainilla', '1 cdta']],
    steps: ['Bate mantequilla con azúcar, agrega huevos de a uno.', 'Suma leche y vainilla.', 'Incorpora harina con polvo de hornear.', 'Hornea en molde enmantequillado 40 min a 180 °C.'] },
  { id: 'r43', name: 'Galletas de avena', emoji: '🍪', cat: 'Postre', time: '30 min', diff: 1,
    ing: [['avena', '1 taza'], ['harina', '1/2 taza'], ['azúcar', '1/2 taza'], ['mantequilla', '80 g'], ['huevo', '1']],
    steps: ['Mezcla todo hasta formar una masa.', 'Forma bolitas y aplástalas en una bandeja.', 'Hornea 12–15 min a 180 °C.'] },
  { id: 'r44', name: 'Brownie', emoji: '🍫', cat: 'Postre', time: '40 min', diff: 2,
    ing: [['chocolate', '150 g'], ['mantequilla', '100 g'], ['azúcar', '3/4 taza'], ['huevo', '2'], ['harina', '1/2 taza']],
    steps: ['Derrite chocolate con mantequilla.', 'Agrega azúcar y huevos.', 'Incorpora la harina.', 'Hornea 25 min a 180 °C.'] },
  { id: 'r45', name: 'Leche asada', emoji: '🍮', cat: 'Postre', time: '60 min', diff: 2,
    ing: [['leche', '1 litro'], ['huevo', '5'], ['azúcar', '1 taza'], ['vainilla', '1 cdta']],
    steps: ['Bate huevos con azúcar y vainilla.', 'Agrega la leche.', 'Vierte en una fuente y hornea a baño maría 45 min a 180 °C.'] },
  { id: 'r46', name: 'Arroz con leche', emoji: '🍚', cat: 'Postre', time: '45 min', diff: 1,
    ing: [['arroz', '1/2 taza'], ['leche', '1 litro'], ['azúcar', '1/2 taza'], ['canela', 'en rama o polvo']],
    steps: ['Cocina el arroz en la leche con canela a fuego bajo, revolviendo.', 'Cuando esté espeso agrega el azúcar.', 'Sirve tibio o frío con canela.'] },
  { id: 'r47', name: 'Mug cake de chocolate', emoji: '☕', cat: 'Postre', time: '5 min', diff: 1,
    ing: [['harina', '4 cdas'], ['cacao', '2 cdas'], ['azúcar', '3 cdas'], ['huevo', '1'], ['leche', '3 cdas'], ['aceite', '2 cdas']],
    steps: ['Mezcla todo en una taza grande.', 'Microondas 1 min 30 seg.', 'Deja reposar 1 min y disfruta.'] },
  { id: 'r48', name: 'Ensalada de frutas', emoji: '🍉', cat: 'Postre', time: '10 min', diff: 1,
    ing: [['manzana', '1'], ['plátano', '1'], ['naranja', '1'], ['frutilla', '1/2 taza']],
    steps: ['Pica todas las frutas.', 'Mezcla con el jugo de la naranja.', 'Refrigera y sirve.'] },
  { id: 'r49', name: 'Plátano con chocolate', emoji: '🍌', cat: 'Postre', time: '5 min', diff: 1,
    ing: [['plátano', '2'], ['chocolate', '50 g']],
    steps: ['Derrite el chocolate en el microondas de a 20 seg.', 'Corta los plátanos y báñalos con chocolate.', 'Opcional: congela 1 hora.'] },
  { id: 'r50', name: 'Sopaipillas', emoji: '🟠', cat: 'Snack', time: '45 min', diff: 3,
    ing: [['harina', '3 tazas'], ['zapallo', '1 taza cocido'], ['mantequilla', '3 cdas'], ['polvo de hornear', '1 cdta'], ['aceite', 'para freír']],
    steps: ['Muele el zapallo cocido con la mantequilla derretida.', 'Agrega harina, polvo de hornear y sal hasta formar una masa.', 'Estira, corta círculos y pínchalos.', 'Fríe en aceite caliente hasta dorar.'] },
];
